name: Test Direct IP

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository using IP
        run: |
          echo "Cloning using direct IP..."
          git clone http://172.18.0.4:3000/kerber/fluxo-bi-api.git .

      - name: Verify clone success
        run: |
          echo "Files in repository:"
          ls -la
          echo "Found pom.xml:"
          cat pom.xml | head -10
          echo "Java source files:"
          find . -name "*.java" | head -5