name: Test Correct Port

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test both ports
        run: |
          echo "Testing port 3000 (internal)..."
          curl -I http://172.18.0.4:3000/ || echo "Port 3000 failed"
          
          echo "Testing port 3001 (external)..."
          curl -I http://172.18.0.4:3001/ || echo "Port 3001 failed"

      - name: Clone with correct port
        run: |
          echo "Cloning from correct port..."
          git clone http://172.18.0.4:3000/kerber/fluxo-bi-api.git . || \
          git clone http://172.18.0.4:3001/kerber/fluxo-bi-api.git .