name: Test Direct IP

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test network
        run: |
          echo "Testing network connectivity..."
          ping -c 2 gitea || echo "gitea hostname failed"

      - name: Get Gitea IP and clone
        run: |
          # Use container IP directly
          GITEA_IP=$(getent hosts gitea | awk '{ print $1 }')
          echo "Gitea IP: $GITEA_IP"
          git clone http://$GITEA_IP:3000/kerber/fluxo-bi-api.git . || \
          git clone http://172.18.0.2:3000/kerber/fluxo-bi-api.git .