name: CI/CD - Build and Deploy to K3s

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: k3rb3rdock/fluxo-bi-api
  # URL de clone que o runner irá usar, com o token de acesso.
  # Usamos o IP do host (que o runner consegue alcançar via host.docker.internal)
  # e a porta mapeada do Gitea (3001).
  CLONE_URL: http://oauth2:${{ secrets.ACTION_TOKEN }}@host.docker.internal:3001/${{ gitea.repository }}.git

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o clone manualmente usando a URL que NÓS controlamos.
      - name: Checkout repository
        run: |
          echo "Cloning repository manually from host..."
          # Adiciona uma configuração extra para que o git confie no repositório
          git config --global --add safe.directory /workspace/${{ gitea.repository }}
          git clone --branch ${{ gitea.ref_name }} ${{ env.CLONE_URL }} .
          echo "Clone complete."

      # Passo 2: Configurar o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # O resto da pipeline permanece exatamente o mesmo
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ gitea.sha }}

      - name: Deploy to K3s
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            # Corrigindo o caminho para a pasta k8s
            sed -i 's|image:.*|image: ${{ env.IMAGE_NAME }}:${{ gitea.sha }}|g' k8s/dev.yaml
            kubectl apply -f k8s/dev.yaml
            echo "Deploy concluído com a imagem ${{ env.IMAGE_NAME }}:${{ gitea.sha }}"
