name: Test Runner Fixed

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify checkout
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repository:"
          ls -la
          echo "Check for Java files:"
          find . -name "*.java" -o -name "pom.xml" | head -5