name: Test Direct IP Fixed

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository using direct IP
        run: |
          echo "Cloning repository from 172.18.0.4:3000..."
          git clone http://172.18.0.4:3000/kerber/fluxo-bi-api.git .

      - name: Verify repository contents
        run: |
          echo "Current directory:"
          pwd
          echo "Repository files:"
          ls -la
          echo "Found pom.xml:"
          ls -la pom.xml
          echo "Java files count:"
          find . -name "*.java" | wc -l