name: Debug Test

on:
  push:
    branches: [ main, master ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Basic test
        run: |
          echo "Testing runner..."
          pwd
          ls -la
          whoami

      - name: Test checkout
        uses: actions/checkout@v3

      - name: After checkout
        run: |
          echo "After checkout:"
          pwd
          ls -la