name: Test Manual Checkout

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Manual git clone
        run: |
          git clone http://gitea:3000/kerber/fluxo-bi-api.git .
          echo "Repository cloned successfully!"
          ls -la
          find . -name "pom.xml"