name: Test Internal Network

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone using internal network
        run: |
          echo "Cloning from internal Gitea IP..."
          git clone http://172.18.0.4:3000/kerber/fluxo-bi-api.git .

      - name: Show files
        run: |
          echo "Repository contents:"
          ls -la
          cat pom.xml | head -10