name: Simple Clone Test

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Direct git clone
        run: |
          echo "Tentando clone direto..."
          git clone http://192.168.40.70:3001/kerber/fluxo-bi-api.git . 

      - name: Show files
        run: |
          echo "Arquivos clonados:"
          ls -la
          echo "pom.xml existe:"
          cat pom.xml | head -5