name: CI/CD - Build and Deploy to K3s

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: k3rb3rdock/fluxo-bi-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ gitea.repository }}
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ gitea.sha }}

      - name: Deploy to K3s
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            sed -i 's|image:.*|image: ${{ env.IMAGE_NAME }}:${{ gitea.sha }}|g' k8s/dev.yaml
            kubectl apply -f k8s/dev.yaml
            echo "Deploy concluído com a imagem ${{ env.IMAGE_NAME }}:${{ gitea.sha }}"